CREATE EXTERNAL TABLE `udm_130_customer`(
  `id` string COMMENT 'from deserializer', 
  `tenantid` int COMMENT 'from deserializer', 
  `sourcesystemid` string COMMENT 'from deserializer', 
  `sourcecustomernumber` string COMMENT 'from deserializer', 
  `uuid` string COMMENT 'from deserializer', 
  `sourceaccountnumber` string COMMENT 'from deserializer', 
  `accountid` string COMMENT 'from deserializer', 
  `firstname` string COMMENT 'from deserializer', 
  `middlename` string COMMENT 'from deserializer', 
  `lastname` string COMMENT 'from deserializer', 
  `title` string COMMENT 'from deserializer', 
  `sal` string COMMENT 'from deserializer', 
  `company` string COMMENT 'from deserializer', 
  `email` string COMMENT 'from deserializer', 
  `primaryphone` string COMMENT 'from deserializer', 
  `secondaryphone` string COMMENT 'from deserializer', 
  `cookie` string COMMENT 'from deserializer', 
  `state` string COMMENT 'from deserializer', 
  `preferences` string COMMENT 'from deserializer', 
  `birthyear` int COMMENT 'from deserializer', 
  `birthmonth` int COMMENT 'from deserializer', 
  `birthday` int COMMENT 'from deserializer', 
  `birthdate` bigint COMMENT 'from deserializer', 
  `age` int COMMENT 'from deserializer', 
  `datecreated` bigint COMMENT 'from deserializer', 
  `datemodified` bigint COMMENT 'from deserializer', 
  `deleteflag` boolean COMMENT 'from deserializer', 
  `rowcreated` bigint COMMENT 'from deserializer', 
  `rowmodified` bigint COMMENT 'from deserializer', 
  `batch` string COMMENT 'from deserializer', 
  `emailstatus` string COMMENT 'from deserializer', 
  `gender` string COMMENT 'from deserializer', 
  `mobilephone` string COMMENT 'from deserializer', 
  `mobileadvertisingid` string COMMENT 'from deserializer', 
  `mobiledeviceid` string COMMENT 'from deserializer', 
  `namecodes` string COMMENT 'from deserializer', 
  `donotemail` string COMMENT 'from deserializer', 
  `donotcall` string COMMENT 'from deserializer', 
  `donottext` string COMMENT 'from deserializer', 
  `donotmail` string COMMENT 'from deserializer', 
  `source` string COMMENT 'from deserializer', 
  `primaryphonevalidity` string COMMENT 'from deserializer', 
  `secondaryphonevalidity` string COMMENT 'from deserializer', 
  `mobilephonevalidity` string COMMENT 'from deserializer', 
  `c_brandid` string COMMENT 'from deserializer', 
  `phonevalidationresultcodes` string COMMENT 'from deserializer')
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.hbase.SaltedHBaseSerDe' 
STORED BY 
  'org.apache.hadoop.hive.hbase.SaltedHBaseStorageHandler' 
WITH SERDEPROPERTIES ( 
  'hbase.columns.mapping'=':key,f:s1,f:s2,f:s3,f:s4,f:s5,f:s6,f:s7,f:s8,f:s9,f:s10,f:s11,f:s12,f:s13,f:s14,f:s15,f:s16,f:s17,f:s18,f:s19,f:s20,f:s21,f:s22,f:s23,f:s24,f:s25,f:s26,f:s27,f:s28,f:s29,f:s30,f:s31,f:s32,f:s33,f:s34,f:s35,f:s36,f:s37,f:s38,f:s39,f:s40,f:s41,f:s42,f:s43,f:s44,f:s45', 
  'serialization.format'='1')
LOCATION
  'hdfs://agiloneCluster:8020/user/hive/warehouse/tenant_130.db/udm_130_customer'
TBLPROPERTIES (
  'COLUMN_STATS_ACCURATE'='false', 
  'agilone.batch'='1', 
  'agilone.batch.end'='9223372036854775807', 
  'agilone.partition'='40', 
  'agilone.ssid'='0', 
  'agilone.table'='-632143041', 
  'agilone.tenant'='130', 
  'hbase.table.name'='pod_GeorgiaPacific', 
  'numFiles'='0', 
  'numRows'='-1', 
  'rawDataSize'='-1', 
  'totalSize'='0', 
  'transient_lastDdlTime'='1519949664')