CREATE EXTERNAL TABLE `udm_130_Event`(
  `id` string COMMENT 'from deserializer', 
  `tenantid` int COMMENT 'from deserializer', 
  `sourcesystemid` string COMMENT 'from deserializer', 
  `sourcesubsystemid` string COMMENT 'from deserializer', 
  `cookie` string COMMENT 'from deserializer', 
  `sessionid` string COMMENT 'from deserializer', 
  `variables` string COMMENT 'from deserializer', 
  `type` string COMMENT 'from deserializer', 
  `category` string COMMENT 'from deserializer', 
  `subtype` string COMMENT 'from deserializer', 
  `eventtimestamp` bigint COMMENT 'from deserializer', 
  `sourcecustomernumber` string COMMENT 'from deserializer', 
  `customerid` string COMMENT 'from deserializer', 
  `email` string COMMENT 'from deserializer', 
  `language` string COMMENT 'from deserializer', 
  `ipaddress` string COMMENT 'from deserializer', 
  `referer` string COMMENT 'from deserializer', 
  `country` string COMMENT 'from deserializer', 
  `os` string COMMENT 'from deserializer', 
  `georegion` string COMMENT 'from deserializer', 
  `geocity` string COMMENT 'from deserializer', 
  `geopostalcode` string COMMENT 'from deserializer', 
  `geolatitude` string COMMENT 'from deserializer', 
  `geolongitude` string COMMENT 'from deserializer', 
  `geoareacode` string COMMENT 'from deserializer', 
  `geoorganization` string COMMENT 'from deserializer', 
  `geocontinent` string COMMENT 'from deserializer', 
  `sourcelistnumber` string COMMENT 'from deserializer', 
  `linkname` string COMMENT 'from deserializer', 
  `url` string COMMENT 'from deserializer', 
  `sourcemessagenumber` string COMMENT 'from deserializer', 
  `messageid` string COMMENT 'from deserializer', 
  `bodytype` string COMMENT 'from deserializer', 
  `anonymous` boolean COMMENT 'from deserializer', 
  `sourceproductnumber` string COMMENT 'from deserializer', 
  `productid` string COMMENT 'from deserializer', 
  `sourceproductcategorynumber` string COMMENT 'from deserializer', 
  `productcategoryid` string COMMENT 'from deserializer', 
  `brandid` string COMMENT 'from deserializer', 
  `sourcetransactionnumber` string COMMENT 'from deserializer', 
  `transactionid` string COMMENT 'from deserializer', 
  `containerid` string COMMENT 'from deserializer', 
  `segmentid` string COMMENT 'from deserializer', 
  `userclient` string COMMENT 'from deserializer', 
  `customerstate` string COMMENT 'from deserializer', 
  `browser` string COMMENT 'from deserializer', 
  `browsertype` string COMMENT 'from deserializer', 
  `operatingsystem` string COMMENT 'from deserializer', 
  `devicetype` string COMMENT 'from deserializer', 
  `rowcreated` bigint COMMENT 'from deserializer', 
  `rowmodified` bigint COMMENT 'from deserializer', 
  `batch` string COMMENT 'from deserializer', 
  `domain` string COMMENT 'from deserializer', 
  `searchterm` string COMMENT 'from deserializer', 
  `source` string COMMENT 'from deserializer', 
  `realtimerequestnumber` string COMMENT 'from deserializer')
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.hbase.SaltedHBaseSerDe' 
STORED BY 
  'org.apache.hadoop.hive.hbase.SaltedHBaseStorageHandler' 
WITH SERDEPROPERTIES ( 
  'hbase.columns.mapping'=':key,f:s1,f:s2,f:s3,f:s4,f:s5,f:s6,f:s7,f:s8,f:s9,f:s10,f:s11,f:s12,f:s13,f:s14,f:s15,f:s16,f:s17,f:s18,f:s19,f:s20,f:s21,f:s22,f:s23,f:s24,f:s25,f:s26,f:s27,f:s28,f:s29,f:s30,f:s31,f:s32,f:s33,f:s34,f:s35,f:s36,f:s37,f:s38,f:s39,f:s40,f:s41,f:s42,f:s43,f:s44,f:s45,f:s46,f:s47,f:s48,f:s49,f:s50,f:s51,f:s52,f:s53,f:s54,f:s55', 
  'serialization.format'='1')
LOCATION
  'hdfs://agiloneCluster:8020/user/hive/warehouse/tenant_130.db/udm_130_event'
TBLPROPERTIES (
  'COLUMN_STATS_ACCURATE'='false', 
  'agilone.batch'='1', 
  'agilone.batch.end'='9223372036854775807', 
  'agilone.partition'='40', 
  'agilone.ssid'='0', 
  'agilone.table'='-2061085991', 
  'agilone.tenant'='130', 
  'hbase.table.name'='pod_GeorgiaPacific', 
  'numFiles'='0', 
  'numRows'='-1', 
  'rawDataSize'='-1', 
  'totalSize'='0', 
  'transient_lastDdlTime'='1519949624')
